version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: thabat-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: thabat
      POSTGRES_USER: thabat
      POSTGRES_PASSWORD: thabat_dev_2024
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
